source 'https://rubygems.org'

group :frontend do
  gem 'compass',        '<= 0.13'
  # Build compass sprites faster with oily_png.
  gem 'sass',           '~> 3.2.0'
  gem 'zen-grids',      '1.4'
end
