<?php


define('DEFAULT_MASS', 'ounces');

define('DEFAULT_VOLUME', 'gallons');

define('DEFAULT_ENERGY', 'therms');

define('DEFAULT_TEMPERATURE', 'F');

define('DEFAULT_CURRENCY', 'USD');

/**
 * Implements hook_menu().
 * @return array
 */
function xeros_report_menu() {

  $items = array();

  $items['ws/dashboard'] = array(
    'title' =>t(''),
    'page callback' => 'ws_dashboard',
    'page arguments' => array(2,3,4,5),
    'access arguments' => array('xeros report dashboard'),
    'file' => 'ws/dashboard.inc'
  );
  $items['report/dashboard'] = array(
    'title' => t('Operational Dashboard'),
    'page callback' => 'report_dashboard',
    'page arguments' => array(),
    'access arguments' => array('xeros report dashboard'),
    'file' => 'report/dashboard.inc'
  );
  $items['ws/health-detail'] = array(
    'title' => t(''),
    'page callback' => 'ws_health',
    'page arguments' => array(2,3,4),
    'access arguments' => array('xeros report health'),
    'file' => 'ws/health.inc'
  );
  $items['report/health'] = array(
    'title' => t('Health Detail'),
    'page callback' => 'report_health',
    'page arguments' => array(),
    'access callback' => 'user_access',
    'access arguments' => array('xeros report health'),
    'file' => 'report/health.inc'
  );
  $items['config/static-values'] = array(
    'title' => t('Static Values'),
    'page callback' => 'config_static_values',
    'page arguments' => array(),
    'access arguments' => array('xeros admin'),
    'file' => 'config.inc'
  );

  return $items;
}
/**
 *
 * Implements hook_entity_info().
 */
function xeros_report_entity_info() {
  $info = array();

  $info['xeros_static_values'] = array(
    'label' => t('Static Values'),
    'base table' => 'xeros_static_values',
    'entity keys' => array(
      'bundle' => 'bundle',
      'name' => 'name'
    )
  );
  return $info;
}

/**
 * Implements hook_theme
 *
 * Define some custom report templates
 * @return array
 */
function xeros_report_theme() {
  $themes = array (
    'xeros_report_dashboard_template' => array(
      'template' => 'templates/node--dashboard',
      'arguments' => array(),
    ),
    'xeros_report_health_template' => array(
      'template' => 'templates/node--health',
      'arguments' => array(),
    ),
    'block_location_picker' => array(
      'variables' => array(),
      'template' => 'templates/block--location-picker',
    ),
  );
  return $themes;
}


//implementation of hook_block_info
function xeros_report_block_info() {
  $blocks = array();
  $blocks['location_picker'] = array(
    'info' => t('Location Picker'),
  );

  return $blocks;
}

//implementation of hook_block_view
function xeros_report_block_view($delta='') {
  $block = array();

  switch($delta) {
//    case 'location_picker' :
//      $block['subject'] = '';
//      $block['content'] = 'Hello World';
//      break;
    case 'location_picker' :
      $variables = array(); //do stuff here
      $block['subject'] = '';
      $block['content'] = theme('block_location_picker', $variables);
      break;
  }
  return $block;
}

function xeros_report_permission() {
  return array(
    'xeros report dashboard' => array(
      'title' => t('View Dashboard Report'),
      'description' => t('Roles with this permission have the ability to access the dashboard report'),
    ),
    'xeros report health' => array(
      'title' => t('View Health Report'),
      'description' => t('Roles with this permission have the ability to access the health report'),
    )
  );
}

function xeros_report_variable_group_info() {

  $groups = array();

  $groups['units'] = array(
      'title' => t('Units'),
      'description' => t('Language Units'),
      'access' => 'administer site configuration',
      'path' => array('admin/config/system/units'),
  );

  return $groups;
}
