<?php

/**
 * Implements hook_menu()
 *
 * @return mixed
 */
function xeros_admin_menu() {
  $items['config/machines'] = array(
    'title' => 'Machine Listing',
    'page callback' => 'machine_listing',
    'page arguments' => array(),
    'access arguments' => array('xeros admin'),
    'file' => 'xeros_admin_machines.inc',
  );
  $items['config/machine'] = array(
    'title' => 'Machine Configuration',
    'page callback' => 'machine_edit_page',
    'page arguments' => array(),
    'access arguments' => array('xeros admin'),
    'file' => 'xeros_admin_machines.inc',
  );
  $items['config/locations'] = array(
    'title' => 'Location Listing',
    'page callback' => 'location_listing',
    'page arguments' => array(),
    'access arguments' => array('xeros admin'),
    'file' => 'xeros_admin_locations.inc'
  );
  $items['config/location'] = array(
    'title' => 'Location Configuration',
    'page callback' => 'location_edit_page',
    'page arguments' => array(),
    'access arguments' => array('xeros admin'),
    'file' => 'xeros_admin_locations.inc',
  );


  return $items;
}