<?php

require_once(drupal_get_path('module', 'xeros_app') . '/user_profile_form.inc');

/**
 * Implements hook_menu()
 *
 * @return mixed
 */
function xeros_app_menu() {
  $items['ws/location'] = array(
    'title' => 'Location Web Service',
    'page callback' => 'ws_location',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'file' => 'ws_location.inc'
  );
  $items['ws/company'] = array(
    'title' => 'Company Web Service',
    'page callback' => 'ws_company',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'file' => 'ws_company.inc'
  );
  $items['ws/industry/averages'] = array(
    'title' => 'Industry Averages Web Service',
    'page callback' => 'ws_industry_averages',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'file' => 'ws_industry_averages.inc'
  );
  return $items;
}

function xeros_app_permission() {
  return array(
    'xeros app' => array(
      'title' => t('Xeros App Access'),
      'description' => t('Roles with this permission have the ability to access the Xeros App'),
    )
  );
}

function xeros_app_preprocess_html(&$variables, $hook) {
  $path = drupal_get_path('module', 'xeros_app');

  // Libraries common to all modules
  drupal_add_js($path . '/libs/underscore-min.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/alertFallback.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Format.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/handlebars.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/HandlebarsHelpers.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/kalendae/kalendae.standalone.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/spin.min.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/canvg-1.3/rgbcolor.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/canvg-1.3/StackBlur.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/canvg-1.3/canvg.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/libs/d3.min.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));

  // Custom controls
  drupal_add_js($path . '/js/Controls.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-Dropdown.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-TimeSelect.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-CompanySelect.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-ReportSelect.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-MachineNav.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-Spinner.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
  drupal_add_js($path . '/js/Controls-Pdf.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));


  // Utility modules common to all drupal modules
  drupal_add_js($path . '/js/Utils.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
//  drupal_add_js($path . '/js/Error.js', array('scope' => 'footer', 'weight' => 100, 'preprocess' => TRUE));

  // Custom app code for logged in users only
  $company = (object) array('nid' => '""', 'title' => '');
  $location = (object) array('nid' => '""', 'title' => '');

  // If user is logged in (0 is anonymous)
  if ( $variables['user']->uid > 0 ) {
    drupal_add_js(drupal_get_path('module', 'xeros_app') . '/js/Location.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
    drupal_add_js(drupal_get_path('module', 'xeros_app') . '/js/Company.js', array('scope' => 'footer', 'weight' => -1, 'preprocess' => TRUE));
    drupal_add_js(drupal_get_path('module', 'xeros_app') . '/js/User.js', array('scope' => 'footer', 'weight' => 10, 'preprocess' => TRUE));
    // Add display elements which are bound to the User control
    drupal_add_js($path . '/js/Display.js', array('scope' => 'footer', 'weight' => 10, 'preprocess' => TRUE));
    drupal_add_js($path . '/js/Controls-Csv.js', array('scope' => 'footer', 'weight' => 10, 'preprocess' => TRUE));
    drupal_add_js($path . '/js/Controls-AdminMenu.js', array('scope' => 'footer', 'weight' => 10, 'preprocess' => TRUE));

    $u = user_load($variables['user']->uid);

    $variables['user']->company = "No company assigned";
    $variables['user']->location = "No location assigned";

    if (isset($u->field_company['und'][0]['target_id'])) {
      $company = node_load($u->field_company['und'][0]['target_id']);
      $variables['user']->company = $company->title;
    }
    if (isset($u->field_location['und'][0]['target_id'])) {
      $location = node_load($u->field_location['und'][0]['target_id']);
      $variables['user']->location = $location->title;
    }

    // This is always the user's company and location.  This can only be overridden in the User's account settings.
    drupal_add_js('jQuery(document).ready(function () {
        FF.User.company.id = ' . $company->nid . ';
        FF.User.company.title = "' . $company->title . '";
        FF.User.location.id =  ' . $location->nid . ';
        FF.User.location.title =  "' . $location->title . '";
    });',
      array('type' => 'inline', 'scope' => 'footer', 'weight' => 14)
    );
    drupal_add_js('jQuery(document).ready(function () {
        FF.User.init();
    });',
      array('type' => 'inline', 'scope' => 'footer', 'weight' => 14)
    );
  } else {
  }
}


function xeros_app_user_logout($account) {
  // Clear all the application cookies so we don't pass the cookies on to another user.
  foreach ( $_COOKIE as $key => $value) {
    if ( preg_match('/^session/', $key) == 1 ) {
      setcookie($key, '', time()-1000);
      setcookie($key, '', time()-1000 , '/');
    }
  }
}

function xeros_app_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#form_id']) && $form['#form_id'] == 'user_profile_form') {
    // TODO: Change to checking for a permission instead of a role
    if ( !in_array('administrator', $GLOBALS['user']->roles ) ) {
      $form['field_company']['#access'] = false;
      $form['field_location']['#access'] = false;
      $form['picture']['#access'] = false;
      $form['timezone']['#access'] = false;
    }
  }
}