ff_xeros:
    resource: "@FFXerosBundle/Controller/"
    type:     annotation
    prefix:   /

report:
    type:   rest
    resource:   FF\XerosBundle\Controller\ReportController
csv:
    type:   annotation
    resource:   FF\XerosBundle\Controller\CSVController